-- Sets a vanilla ingredient as a valid shake crafting item.
function setBlenderShakeIngredient(itemName, hungerValue)
	local item = ScriptManager.instance:getItem("Base." .. itemName)
	if item then
		item:DoParam("EvolvedRecipe = JunkiezBlendedShake:"..hungerValue)
	end
end

function setShakeIngredient(itemName, hungerValue)
	local item = ScriptManager.instance:getItem("Base." .. itemName)
	if item then
		item:DoParam("EvolvedRecipe = JunkiezShake:"..hungerValue)
	end
end

-- Add ingredients for use in creating shakes

-- Canned Foods
setBlenderShakeIngredient("CannedCarrotsOpen",4)
setBlenderShakeIngredient("CannedTomatoOpen",4)
setBlenderShakeIngredient("CannedFruitCocktailOpen",5)
setBlenderShakeIngredient("CannedFruitBeverageOpen",5)
setBlenderShakeIngredient("CannedMilkOpen",2)
setBlenderShakeIngredient("CannedPeachesOpen",5)

setShakeIngredient("CannedFruitCocktailOpen",5)
setShakeIngredient("CannedFruitBeverageOpen",5)
setShakeIngredient("CannedMilkOpen",2)
-- Fruits
setBlenderShakeIngredient("Avocado",8)
setBlenderShakeIngredient("Zucchini",5)
setBlenderShakeIngredient("Carrots",4)
setBlenderShakeIngredient("Eggplant",8)
setBlenderShakeIngredient("BerryBlack",10)
setBlenderShakeIngredient("BerryBlue",10)
setBlenderShakeIngredient("BerryGeneric1",5)
setBlenderShakeIngredient("BerryGeneric2",10)
setBlenderShakeIngredient("BerryGeneric3",5)
setBlenderShakeIngredient("BerryGeneric4",10)
setBlenderShakeIngredient("BerryGeneric5",10)
setBlenderShakeIngredient("BerryPoisonIvy",5)
setBlenderShakeIngredient("Peach",6)
setBlenderShakeIngredient("Pineapple",6)
setBlenderShakeIngredient("Cherry",3)
setBlenderShakeIngredient("Watermelon",10)
setBlenderShakeIngredient("WatermelonSliced",6)
setBlenderShakeIngredient("WatermelonSmashed",12)
setBlenderShakeIngredient("Grapes",5)
setBlenderShakeIngredient("Orange",6)
setBlenderShakeIngredient("Apple",8)
setBlenderShakeIngredient("Banana",16)
-- Meat/Game
setBlenderShakeIngredient("Tofu",5)
-- Liquids
setBlenderShakeIngredient("Bleach",2)
setBlenderShakeIngredient("JuiceBox",2)
setBlenderShakeIngredient("WhiskeyFull",5)
setBlenderShakeIngredient("Pop",2)
setBlenderShakeIngredient("Pop2",2)
setBlenderShakeIngredient("Pop3",2)
setBlenderShakeIngredient("PopBottle",2)
setBlenderShakeIngredient("BeerCan",4)
setBlenderShakeIngredient("BeerBottle",3)
setBlenderShakeIngredient("Wine",2)
setBlenderShakeIngredient("Wine2",2)

setShakeIngredient("Bleach",2)
setShakeIngredient("JuiceBox",2)
setShakeIngredient("WhiskeyFull",5)
setShakeIngredient("Pop",2)
setShakeIngredient("Pop2",2)
setShakeIngredient("Pop3",2)
setShakeIngredient("PopBottle",2)
setShakeIngredient("BeerCan",4)
setShakeIngredient("BeerBottle",3)
setShakeIngredient("Wine",2)
setShakeIngredient("Wine2",2)
-- Candies
setBlenderShakeIngredient("Icecream",5)
setBlenderShakeIngredient("IcecreamMelted",5)
setBlenderShakeIngredient("Peppermint",10)
setBlenderShakeIngredient("Candycane",5)
setBlenderShakeIngredient("CookieChocolateChip",5)
setBlenderShakeIngredient("SunflowerSeeds",5)
setBlenderShakeIngredient("MintCandy",2)
setBlenderShakeIngredient("Chocolate",5)
setBlenderShakeIngredient("Milk",5)

setShakeIngredient("Icecream",5)
setShakeIngredient("IcecreamMelted",5)
setShakeIngredient("Milk",5)
-- Forage
setBlenderShakeIngredient("WildGarlic2",1)
setBlenderShakeIngredient("CommonMallow",1)
setBlenderShakeIngredient("LemonGrass",1)
setBlenderShakeIngredient("BlackSage",1)
setBlenderShakeIngredient("Ginseng",1)
setBlenderShakeIngredient("Rosehips",2)
setBlenderShakeIngredient("GrapeLeaves",4)
setBlenderShakeIngredient("Violets",2)
setBlenderShakeIngredient("WildEggs",7)
-- Others
setBlenderShakeIngredient("Salt",1)
setBlenderShakeIngredient("Pepper",1)
setBlenderShakeIngredient("PeanutButter",5)
setBlenderShakeIngredient("Coffee2",5)
setBlenderShakeIngredient("Teabag2",5)
setBlenderShakeIngredient("Oatmeal",2)
setBlenderShakeIngredient("Sugar",1)
setBlenderShakeIngredient("Yoghurt",5)
setBlenderShakeIngredient("OatsRaw",5)
setBlenderShakeIngredient("CocoaPowder",5)
setBlenderShakeIngredient("Grapefruit",5)
setBlenderShakeIngredient("Hotsauce",2)
setBlenderShakeIngredient("Lime",2)
setBlenderShakeIngredient("Lemon",2)
setBlenderShakeIngredient("MapleSyrup",3)
setBlenderShakeIngredient("Pear",5)
setBlenderShakeIngredient("GranolaBar",5)
setBlenderShakeIngredient("Mango",5)
setBlenderShakeIngredient("Pumpkin",5)
setBlenderShakeIngredient("HalloweenPumpkin",5)
setBlenderShakeIngredient("BeautyBerry",5)
setBlenderShakeIngredient("Dandelions",2)
setBlenderShakeIngredient("Basil",2)
setBlenderShakeIngredient("Dandelions",1)
setBlenderShakeIngredient("Chives",1)
setBlenderShakeIngredient("Cilantro",1)
setBlenderShakeIngredient("Oregano",1)
setBlenderShakeIngredient("Parsley",1)
setBlenderShakeIngredient("Rosemary",1)
setBlenderShakeIngredient("Sage",1)
setBlenderShakeIngredient("Thyme",1)
setBlenderShakeIngredient("HollyBerry",5)
setBlenderShakeIngredient("Nettles",2)
setBlenderShakeIngredient("GingerRoot",1)
setBlenderShakeIngredient("Thistle",2)
setBlenderShakeIngredient("WinterBerry",5)
setBlenderShakeIngredient("SugarPacket",1)
setBlenderShakeIngredient("ChocolateCoveredCoffeeBeans",5)

setShakeIngredient("Salt",1)
setShakeIngredient("Pepper",1)
setShakeIngredient("PeanutButter",5)
setShakeIngredient("Coffee2",5)
setShakeIngredient("Teabag2",5)
setShakeIngredient("Sugar",1)
setShakeIngredient("Yoghurt",5)
setShakeIngredient("CocoaPowder",5)
setShakeIngredient("Hotsauce",2)
setShakeIngredient("Lime",2)
setShakeIngredient("Lemon",2)
setShakeIngredient("MapleSyrup",3)
setShakeIngredient("SugarPacket",1)