-- Sets a vanilla ingredient as a valid shake crafting item.
function setShakeIngredient(itemName, hungerValue)
	local item = ScriptManager.instance:getItem("Base." .. itemName)
	if item then
		item:DoParam("EvolvedRecipe = JunkiezShake:"..hungerValue)
	end
end

-- Add ingredients for use in creating shakes

-- Canned Foods
setShakeIngredient("CannedCarrotsOpen",4)
setShakeIngredient("CannedTomatoOpen",4)
setShakeIngredient("CannedFruitCocktailOpen",5)
setShakeIngredient("CannedFruitBeverageOpen",5)
setShakeIngredient("CannedMilkOpen",2)
setShakeIngredient("CannedPeachesOpen",5)
-- Fruits
setShakeIngredient("Avocado",8)
setShakeIngredient("Zucchini",5)
setShakeIngredient("Carrots",4)
setShakeIngredient("Eggplant",8)
setShakeIngredient("BerryBlack",10)
setShakeIngredient("BerryBlue",10)
setShakeIngredient("BerryGeneric1",5)
setShakeIngredient("BerryGeneric2",10)
setShakeIngredient("BerryGeneric3",5)
setShakeIngredient("BerryGeneric4",10)
setShakeIngredient("BerryGeneric5",10)
setShakeIngredient("BerryPoisonIvy",5)
setShakeIngredient("Peach",6)
setShakeIngredient("Pineapple",6)
setShakeIngredient("Cherry",3)
setShakeIngredient("Watermelon",10)
setShakeIngredient("WatermelonSliced",6)
setShakeIngredient("WatermelonSmashed",12)
setShakeIngredient("Grapes",5)
setShakeIngredient("Orange",6)
setShakeIngredient("Apple",8)
setShakeIngredient("Banana",16)
-- Meat/Game
setShakeIngredient("Tofu",5)
-- Liquids
setShakeIngredient("Bleach",2)
setShakeIngredient("JuiceBox",2)
setShakeIngredient("WhiskeyFull",5)
setShakeIngredient("Pop",2)
setShakeIngredient("Pop2",2)
setShakeIngredient("Pop3",2)
setShakeIngredient("PopBottle",2)
setShakeIngredient("BeerCan",4)
setShakeIngredient("BeerBottle",3)
setShakeIngredient("Wine",2)
setShakeIngredient("Wine2",2)
-- Candies
setShakeIngredient("Icecream",5)
setShakeIngredient("IcecreamMelted",5)
setShakeIngredient("Peppermint",10)
setShakeIngredient("Candycane",5)
setShakeIngredient("CookieChocolateChip",5)
setShakeIngredient("SunflowerSeeds",5)
setShakeIngredient("MintCandy",2)
setShakeIngredient("Chocolate",5)
setShakeIngredient("Milk",5)
-- Forage
setShakeIngredient("WildGarlic2",1)
setShakeIngredient("CommonMallow",1)
setShakeIngredient("LemonGrass",1)
setShakeIngredient("BlackSage",1)
setShakeIngredient("Ginseng",1)
setShakeIngredient("Rosehips",2)
setShakeIngredient("GrapeLeaves",4)
setShakeIngredient("Violets",2)
setShakeIngredient("WildEggs",7)
-- Others
setShakeIngredient("Salt",1)
setShakeIngredient("Pepper",1)
setShakeIngredient("PeanutButter",5)
setShakeIngredient("Coffee2",5)
setShakeIngredient("Teabag2",5)
setShakeIngredient("Oatmeal",2)
setShakeIngredient("Sugar",1)
setShakeIngredient("Yoghurt",5)
setShakeIngredient("OatsRaw",5)
setShakeIngredient("CocoaPowder",5)
setShakeIngredient("Grapefruit",5)
setShakeIngredient("Hotsauce",2)
setShakeIngredient("Lime",2)
setShakeIngredient("MapleSyrup",3)
setShakeIngredient("Pear",5)
setShakeIngredient("GranolaBar",5)
setShakeIngredient("Mango",5)
setShakeIngredient("Pumpkin",5)
setShakeIngredient("HalloweenPumpkin",5)
setShakeIngredient("BeautyBerry",5)
setShakeIngredient("Dandelions",2)
setShakeIngredient("Basil",2)
setShakeIngredient("Dandelions",1)
setShakeIngredient("Chives",1)
setShakeIngredient("Cilantro",1)
setShakeIngredient("Oregano",1)
setShakeIngredient("Parsley",1)
setShakeIngredient("Rosemary",1)
setShakeIngredient("Sage",1)
setShakeIngredient("Thyme",1)
setShakeIngredient("HollyBerry",5)
setShakeIngredient("Nettles",2)
setShakeIngredient("GingerRoot",1)
setShakeIngredient("Thistle",2)
setShakeIngredient("WinterBerry",5)
setShakeIngredient("SugarPacket",1)
setShakeIngredient("ChocolateCoveredCoffeeBeans",5)